### ISSUE TITLE
error on startup: poly-R/:catch: Symbol’s value as variable is void: poly-noweb-innermode

### ISSUE THREAD

**Issue by andyptt21** [polymode/poly-R#11]
I've been using poly-R for months but upon the latest update I cannot get it to load properly. I've tried two strategies for loading:

 (use-package poly-R
   :ensure t)

Which results in the error:

poly-R/:catch: Symbol’s value as variable is void: poly-noweb-innermode

I then tried to be more explicit about the load paths, by doing:

(use-package polymode
  :ensure t
  :pin melpa-stable
  :init
  (setq load-path 		
	(append '("~/.emacs.d/elpa/polymode-20190508.1847/"
		  "~/.emacs.d/elpa/polymode-20190508.1847/modes"
		  "~/.emacs.d/elpa/polymode-20190508.1847/modes/poly-R"
		  "~/.emacs.d/elpa/polymode-20190508.1847/modes/poly-org"
		  "~/.emacs.d/elpa/polymode-20190508.1847/modes/poly-noweb"
		  "~/.emacs.d/elpa/polymode-20190508.1847/modes/poly-markdown"
		  ) load-path))
  (require 'poly-R)		
  (require 'poly-markdown)
  (require 'poly-noweb)
  (require 'poly-org))

Which results in the same error. Any idea what the problem might be? Sorry that this is very similar to the last posted issue but I've been unable to find a fix.

**Comment by vspinu** [comment]
You need to update poly-noweb as well.

**Comment by vspinu** [comment]
Wait, you have it up to date. I think somehow the older poly-noweb is loaded. Try to navigate to poly-noweb-mode and see where it brings you. Also look at the load-path and see if you end up with multiple versions of poly-noweb.

**Comment by andyptt21** [comment]
It works! I deleted all the older noweb versions and made sure the newly updated one was the only one in my load path. Turns out the same thing happened to poly-markdown. I guess something weird happened when I decided to 'update all' in the list-packages buffer. Thanks for your prompt replies! Love this software.
