### ISSUE TITLE
Rd mode uses percent for comment-start

### ISSUE THREAD

**Issue by kwstat** [polymode/poly-R#13]
In Rd mode, ESS is setting comment-start to "% %.

See:
https://github.com/emacs-ess/ESS/blob/bc5a7d9fe954aceaab36f3eb5de30112a541c433/lisp/ess-rd.el

I find this annoying and wish it were set to "# " so that I can comment code in the examples section.  Is this a reasonable change?

**Comment by kwstat** [comment]
Sorry, I meant to post this in ESS.

**Comment by vspinu** [comment]
I you are using it with polymode then it should be #.
