### ISSUE TITLE
Losing track of org buffer with smartparens

### ISSUE THREAD

**Issue by markabney** [polymode/poly-R#18]
Not sure if this is a poly-R, poly-org or smartparens issue. With smartparens on, when leaving an R block in a org file, emacs can fail to switch from ESS mode to org mode. This error message appears in the minibuffer: "(pm-switch-to-buffer 62): Wrong type argument: number-or-marker-p, nil"

I can reproduce this with this org file:
`
Test poly org with R.

#+begin_src R 

  x <- 1:3

#+end_src
`

1.  Turn on smartparens
2.  Move point to # character in #+end_src (i.e. beginning of line)
3.  Type character 'd', then backspace (just deleting the typed character)
4. Move point up one line (into R block) then down two lines (out of R block)

At this point the error message appears in the minibuffer and instead of being in org-mode, emacs remains in ESS mode.

I have removed all customizations and only have the following in my init.el file:
`
(require 'package)
(add-to-list 'package-archives
	     '("melpa" . "http://melpa.org/packages/"))
(add-to-list 'package-archives
	     '("org" . "https://orgmode.org/elpa/"))
(setq package-enable-at-startup nil)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)
(require 'bind-key)
(use-package smartparens
  :ensure t)
(use-package poly-org
  :ensure t)
(load-theme 'spacemacs-dark t)
`

**Comment by vspinu** [comment]
Thanks for reporting. Closing in favor of a more general polymode/polymode#255
