### ISSUE TITLE
Cannot evaluate R in flatwhatson/emacs-pgtk-nativecomp build

### ISSUE THREAD

**Issue by bryce-carson** [polymode/poly-R#25]
I recently upgraded to pgtk-nativecomp, now using my forked build here: [Copr bacarson/emacs-pgtk-nativecomp](https://copr.fedorainfracloud.org/coprs/bacarson/emacs-pgtk-nativecomp/).

This build allows Polymode to compile and run (I don't experience polymode/polymode#285).

# Observed Behaviour
I cannot evaluate any R code blocks in Rmd files, nor anything in R files. In both cases, upon `C^c C^j`, I get this message: `ad-Advice-select-window: Wrong type argument: window-live-p, nil`. In order to evaluate anything, I have to use `polymode-export` to run the entire Rmd document's code blocks and regenerate the HTML I'm exporting to.

# Expected Behaviour
- Evaluate code blocks with `C^c C^r` or lines with `C^c C^j`
- Markdown export (`C^c C^c e`) should trigger `polymode-export`, not simply convert MD to HTML

I'm *noobish*, however, so I'm not sure how to properly introspect the issue.

# Emacs Version
## Build Information / Commit
- My Copr build, forked from deathwish/emacs-pgtk-nativecomp, updated to build from flatwhatson/emacs@64425ee0d82632c71839aa615256e9a438e1d62a.
  - The update prevents polymode/poly-R#22 and polymode/polymode#285
- Here is the [RPM spec](https://download.copr.fedorainfracloud.org/results/bacarson/emacs-pgtk-nativecomp/fedora-33-x86_64/02081806-emacs/emacs.spec) used for my Copr build

## Information from `SPC h d s`
```
#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 369cf7519)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
‘‘‘elisp
(html emacs-lisp helm multiple-cursors treemacs)
‘‘‘
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS XIM XWIDGETS GTK3 ZLIB
```
## .spacemacs
- [dotspacemacs.zip](https://github.com/polymode/poly-R/files/6173776/dotspacemacs.zip)
  - `mv dotspacemacs.zip .spacemacs.zip && unzip .spacemacs.zip`

# Package information
## Polymode
```
     Status: Installed in ‘polymode-20200606.1106/’ (unsigned).
    Version: 20200606.1106
     Commit: b3871e946d278a256d95a3bd4615b1df234ad75a
```
## poly-R
```
     Status: Installed in ‘poly-R-20210210.1053/’ (unsigned).
    Version: 20210210.1053
     Commit: c42ff3a4d0da96ccb7f826dca5c6b2eb558a2ab5
```
## Package Install & Compile Order is specific
- Polymode packages should be installed in a specific order.
- If the packages are already installed, reinstall them using `M^x package-reinstall` in this order:

1. ess
2. polymode
3. poly-noweb
4. poly-R
5. poly-markdown

- This is what worked for myself, using Spacemacs and this Copr build.

**Comment by vspinu** [comment]
Do you experience this with just ess? There is no polymode functionality in plain R files. Also none of the packages involved advice of the select-window. So the culprit is likely somewhere else, but who knows.

**Comment by vspinu** [comment]
I cannot even configure emacs with native code as of `configure: error: Installed libgccjit has failed passing the smoke test.`  andI don't have time to get into the weeks of gccjit ATM and figure it out. So, I am afraid I probably won't able to help you here any time sooninsh.

**Comment by bryce-carson** [comment]
> Do you experience this with just ess? There is no polymode functionality in plain R files. Also none of the packages involved advice of the select-window. So the culprit is likely somewhere else, but who knows. 

It occurs in ~Polymode~ buffers (an Rmd document). I tested in a plain .R file buffer *after* observing it in the Rmd document buffer.

**Comment by bryce-carson** [comment]
I'll try with `emacs -Q` and see if I can reproduce it without any Helm or Spacemacs stuff clobbering how I interact eoth Emacs.

**Comment by bryce-carson** [comment]
@vspinu I was able to evaluate a line.

1. `s/beg/start/g` (Unfortunately, I forget which file this is in, and what prompted me to change it).

```elisp
(defun ess-eval-line (&optional vis)
  "Send the current line to the inferior ESS process.
VIS has same meaning as for `ess-eval-region'."
  (interactive "P")
  (let* ((start (point-at-bol))
         (end (point-at-eol))
         (msg (format "Loading line: %s" (buffer-substring start end))))
    (ess-eval-region start end vis msg)))
```
2. `SPC q D` (`restart-stock-emacs-with-packges`, specifying only ess)
3. Open an Rmd file, `M^x ess-eval-line`

I'm still not sure what's going on, nor am I confident that my changes were necessary or that this comment will be helpful to you or anyone else.

**Comment by bryce-carson** [comment]
Changing to Ivy solved my issue, @vspinu. I don't know if the problem was in `ess-eval-line` or if Helm was the culprit all along. As I learn more about Emacs, I'll be able to make a more informed judgement and I'll open an issue with the proper package.

I'm going to close this issue, as the problem is *not* with poly-R.
