### ISSUE TITLE
Call bookdown exporter interactively

### ISSUE THREAD

**Issue by plantarum** [polymode/poly-R#29]
Hello,

I would like to be able to call bookdown to render my Rmd source using the pdf_document2 format. This happens automatically if I include the directive in the Rmd yaml:

```
output:
  bookdown::pdf_document2
```

However, I would like to be able to select this output interactively. It's already defined in `poly-r-bookdown-ess-exporter`, but that exporter isn't offered as an option when I set my exporter (it doesn't have a matching `from` argument).

How can I make poly-R use the bookdown exporter interactively?

**Comment by plantarum** [comment]
I took another look at the exporter functions. #30 addresses one of my use cases, and the part that's more likely to be generally useful.

I could manage this as a personal customization, but as I mentioned in https://github.com/polymode/polymode/issues/302#issue-1008566539 it's not clear if this is possible.

**Comment by vspinu** [comment]
> (it doesn't have a matching from argument).

I am not entirely sure I understand this issue. Do you suggest that something is missing in the current `from` fields?  Would it make sense to add then?

**Comment by plantarum** [comment]
I'm not sure any more. We have the features I was after via the other changes you've merged, and I still don't fully understand how the `poly-r-bookdwon-ess-exporter` works. So this is likely just my misunderstanding.
