### ISSUE TITLE
execute one/some/all R chunks from Rmd buffer in ESS buffer

### ISSUE THREAD

**Issue by timflutre** [polymode/poly-R#3]
Before the refactoring of polymode this summer, some EmacsLisp code existed allowing to interactively execute one/some/all R chunks from a Rmd buffer into an ESS buffer (see [here](https://stackoverflow.com/a/40966640/597069)), which made Emacs+ESS+polymode a very useful replacement of RStudio.

However, the refactoring seems to have broken this code, and an error message points towards `pm-map-over-spans`. Below is a minimal reproducible example tested under Ubuntu 16.04, Emacs 26.1 with all packages up-to-date (ess-20181010.1844, polymode 20181010.2138, poly-R 20181010.2137 and their dependencies).

Here is the Rmd file saved in a file named `test.Rmd`:

    ---
    title: "..."
    author: "..."
    date: "..."
    output: html_document
    ---
    
    ```{r}
    x <- 42
    x
    ```

Here are the Rmd functions saved in a file named `rmd.el`:

```

(eval-when-compile
  (require 'polymode-core)  ;; SO format :('
  (defvar pm/chunkmode))
(declare-function pm-map-over-spans "polymode-core")
(declare-function pm-narrow-to-span "polymode-core")

(defun rmd-insert-chunk (header)
  "Insert an R chunk."
  (interactive "sHeader: ")
	(if (equal "" header)
			(insert (concat "```{r}\n\n```"))
		(insert (concat "```{r " header "}\n\n```")))
  (forward-line -1))

(defun rmd-send-chunk ()
  "Send current R chunk to ess process."
  (interactive)
  (and (eq (oref pm/chunkmode :mode) 'r-mode) ;;'
       (pm-with-narrowed-to-span nil
         (goto-char (point-min))
         (forward-line)
         (ess-eval-region (point) (point-max) nil nil 'R)))) ;;'

(defun rmd-send-buffer (arg)
  "Send all R code blocks in buffer to ess process. With prefix
send regions above point."
  (interactive "P")
  (save-restriction
    (widen)
    (save-excursion
      (pm-map-over-spans
       'rmd-send-chunk (point-min) ;;'
       ;; adjust this point to send prior regions
       (if arg (point) (point-max))))))
```

Here is the workflow:

1. launch Emacs;
2. open the Rmd file via `C-x C-f test.Rmd` in a polymode buffer;
3. put the cursor inside the R chunk and do `C-c C-z` which automatically opens an ESS buffer;
4. load the ELisp functions via `M-x load-file rmd.el`;
5. put the cursor of the polymode buffer inside the R chunk and do `M-x rmd-send-chunk`; at this stage, the following message appears in the ESS buffer: `Error: object 'x' not found`, but the \*Messages\* buffer only displays `Eval region`;
6. put the cursor at the end of the polymode buffer and do `M-x rmd-send-buffer`; at this stage, the following message appears in the mini-buffer as well as in the \*Messages\* buffer: `Wrong number of arguments: (lambda nil "Send current R chunk to ess process." (interactive) (and (eq (eieio-oref pm/chunkmode (quote :mode)) (quote r-mode)) (save-restriction \
(pm-narrow-to-span nil) (goto-char (point-min)) (forward-line) (ess-eval-region (point) (point-max) nil nil (quote R))))), 1`.

By any chance, do you have any idea?

**Comment by vspinu** [comment]
The `*span*` dynamic variable still works but the explicit `span` argument to maped function is now preferred. Just add a dummy `span` argument to your `rmd-send-chunk` and it should work again.

There is a PR polymode/polymode#129 dedicated to this issue. The solution must be a generic one not R specific. I will have a look at it pretty soon now. Closing this in favor of that issue.

**Comment by rmcd1024** [comment]
@timflutre, did you get this working?

**Comment by timflutre** [comment]
@rmcd1024 yes. I'm using the latest code from polymode and poly-R, and then I'm following the explanations here: https://polymode.github.io/usage/

**Comment by rmcd1024** [comment]
Terrific, thank you!
