### ISSUE TITLE
Pandoc/LaTeX errors caused by appending "[exported]" to directory name.

### ISSUE THREAD

**Issue by jkaiwar** [polymode/poly-R#5]
When compiling from Rmarkdown to PDF, poly-R puts intermediate files in a directory `test[exported]_files`. A bug in Pandoc causes the braces to placed around brackets when referring to files in this directory like so:

`\includegraphics{test{[}exported{]}_files/figure-latex/unnamed-chunk-2-1.pdf}`.

This is causes LaTeX compile to fail with the error:

``! Package pdftex.def Error: File `test{[}exported{]}_files/figure-latex/unnamed
-chunk-2-1.pdf' not found: using draft setting.``

Note RMarkdown always fails to compile a pdf document that has square brackets in the filename, due to the same Pandoc bug.

**Comment by jkaiwar** [comment]
On further investigation, this is changed by customizing the variable `polymode-exporter-output-file-format` to `"%s-out"`.

**Comment by vspinu** [comment]
Thanks for reporting this. I think the [exported] postfix should be just replaced with empty string as it was a cause of many complains over the years.
