### ISSUE TITLE
Do I need to configure `poly-r-rmarkdown-template-dirs` manually, even for templates included with installed R packages (e.g. tufte)?

### ISSUE THREAD

**Issue by jerlev** [polymode/poly-R#6]
(note: this question stems from https://emacs.stackexchange.com/questions/47942/missing-rmarkdown-templates-with-poly-r)
I inspected the poly-R source, and I did not find any code that would search for templates in the local R Libraries; it seems all paths must be listed manually in `poly-r-rmarkdown-template-dirs`. Is that right? The reason I am asking is that poly-R's README.md says in a cursory way "RMarkdown templates available through ESS menus and on M-n M-m in Rmd files (poly-r-rmarkdown-create-from-template)", without alluding specifically to the variable `poly-r-rmarkdown-template-dirs`. Also, RStudio also lists installed .Rmd templates automatically, so I thought I might have missed in the poly-R source a call to an R function that would list installed .Rmd templates.

**Comment by vspinu** [comment]
It's automatic. All the ones installed should be shown in the template. For example, install the package `tufte` and a submenu in `RMarkdown > Template > Tufte` will appear. See the doc string of `poly-r-rmarkdown-create-from-template` for a few examples of common packages that provide the templates. Let me know if you find more.

**Comment by vspinu** [comment]
There might be R/ESS/poly-R version mismatch. What versions do you use? You need fairly recent poly-R for this. The relevant R code is [here](https://github.com/polymode/poly-R/blob/master/poly-R.el#L102-L137). 

It boils down to the following:

```R

list_templates <- 
  function(user_dirs) {
    user_dirs <- c(user_dirs, unlist(lapply(user_dirs, list.dirs, recursive = FALSE)))
    list_from_dir <- function(dir, pkg = NULL) {
      pkg_name <- if(is.null(pkg)) 'USER' else pkg
      if (dir.exists(dir)) {
        dirs <- list.dirs(dir, recursive = FALSE)
        for (d in dirs) {
          yaml_file <- file.path(d, 'template.yaml')
          if (file.exists(yaml_file)) {
            yaml <- rmarkdown:::yaml_load_file_utf8(yaml_file)
            if (is.null(desc <- yaml$description)) desc <- 'nil'
            cat(sprintf('(\"%s\" \"%s\" \"%s\" \"%s\")\n', pkg_name, d, yaml$name, desc))
          }
        }
      }
    }
    cat('(\n')
    for (user_dir in user_dirs) {
      files <- list.files(user_dir,  '\\.[Rr]md$', full.names = TRUE)
      for (f in files) {
        name <- sub('\\.[^.]+$','', basename(f))
        cat(sprintf('(\"USER\" \"%s\" \"%s\")\n', f, name))
      }
      list_from_dir(user_dir)
    }
    packages <- sort(unlist(lapply(.libPaths(), dir)))
    for (pkg in packages) {
      template_folder <- system.file('rmarkdown', 'templates', package = pkg)
      list_from_dir(template_folder, pkg)
    }
    cat(')\n')
  }

list_templates(c())
```

and should produce something along:

```

(
("rmarkdown" "/home/vspinu/.lib/3.6.0/rmarkdown/rmarkdown/templates/github_document" "GitHub Document (Markdown)" "Template for documents to be published as GitHub Flavored Markdown.
")
("rmarkdown" "/home/vspinu/.lib/3.6.0/rmarkdown/rmarkdown/templates/html_vignette" "Package Vignette (HTML)" "Template for package vignettes. This customises the basic HTML output to take up as little space as possible.
")
("tufte" "/home/vspinu/.lib/3.6.0/tufte/rmarkdown/templates/tufte_ctex" "Tufte Handout (HTML or PDF in Chinese)" "A Chinese template for creating a handout according to the style of Edward R. Tufte and Richard Feynman.
")
("tufte" "/home/vspinu/.lib/3.6.0/tufte/rmarkdown/templates/tufte_html" "Tufte Handout (HTML or PDF)" "Template for creating a handout according to the style of Edward R. Tufte and Richard Feynman.
")
)
```

**Comment by jerlev** [comment]
Got it. I found an issue with the call to `rmarkdown:::yaml_load_file_utf8`. In recent versions of `rmarkdown` this function has been renamed `yaml_load_file` (https://github.com/rstudio/rmarkdown/commit/8e62228334c7036a30ee3edb6871565d69e54bfb). With that fixed in my local copy of poly-r.el, and after running `byte-compile-file`, the items are found, and the menu now looks as expected.

**Comment by vspinu** [comment]
Thanks for identifying the issue. Should be fixed now.

**Comment by antonellosalis** [comment]
I have the same issue..
