### ISSUE TITLE
Function indirection loop

### ISSUE THREAD

**Issue by mattblackwell** [polymode/poly-R#7]
In version 20190320.2042 of poly-R from melpa, I see the following error during init:

    Symbol's chain of function indirections contains a loop: poly-markdown+r-mode

Removing line 90 from my `poly-R.el` and the corresponding line from `poly-R-autoloads.el` fixes this problem. I think this line is a typo?

    (define-obsolete-function-alias 'poly-markdown+r-mode 'poly-markdown+r-mode "v0.2")

Thanks for a great package!

**Comment by economicist** [comment]
Confirmed, although it's actually line 91 in my `poly-R.el` .

As **mattblackwell** says, the following command: `(define-obsolete-function-alias 'poly-markdown+r-mode 'poly-markdown+r-mode "v0.2")` has the `'poly-markdown+r-mode` entered twice, making the command a self alias and triggering a reference loop.

Fixing line 91 of `poly-R.el` and line 19 of `poly-R-autoloads.el` to correct this allows `poly-R.el` to be compiled without error and `ess-mode` to be launched without error afterward.

**Comment by vspinu** [comment]
Thanks for catching this. I did some heavy renaming and forgot to re-test once things propagated to MELPA.
