### ISSUE TITLE
why does polymode autolaunch R now?

### ISSUE THREAD

**Issue by slyrus** [polymode/poly-R#9]
I'm having nothing but trouble since trying to update to the latest git head. My immediate problem is that when I try to open a .org R file, it wants to immediately launch R, and keeps asking me over and over to start yet another R session. I'm not sure if this is a poly-org or poly-R issue but it has made polymode unusable for me, at least for the moment.

**Comment by vspinu** [comment]
Something is not right with your setup. You can test it without hour config by running `make start` from the git repo.

**Comment by vspinu** [comment]
You probably have something in your R or org hooks which require live process. It might be ESS bug as well.

**Comment by slyrus** [comment]
Ok, I'm going to assume that this is some sort of transient error and close this. Sorry to bother you (again)!
